task: ratio_10_ratio_12

src_img: dataset/homo/infer/modulus/ratio_12/ratio_10_ratio_12/01_21_17_56
src_force: dataset/homo/modulus/force/ratio_10

tar_img: dataset/homo/modulus/image/ratio_12
tar_force: dataset/homo/modulus/force/ratio_12

min_max: force/config/min_max.json

checkpoint: /scratch_tmp/users/k23058530/project/genforce/output/force/modulus/incomplete/ratio12/ratio_10_ratio_12/epoch_40.pth
save_dir: /scratch_tmp/users/k23058530/project/genforce/output/force/modulus/{}

#Train
# train: True
# train_use_checkpoint: True                 
# draw_force: True
# draw_use_checkpoint: False 
     
#Infer
train: False
train_use_checkpoint: True                 
draw_force: True
draw_use_checkpoint: True                

num_workers: 32
batch_size: 4
n_epoch: 40
early_stop: 20
lr: 1e-3   #train 1e-1;fine tune:1e-3
seed: 0

unseen: ["cone","wave","triangle","pacman","cylinder-sh","sphere-s"]
