task: Diamond-I_Array-I

src_img: infer/homo/Diamond-I_Array-I/01_13_11_17
src_force: dataset/homo/force/Diamond-I

tar_img: dataset/homo/image/npy/Array-I
tar_force: dataset/homo/force/Array-I

min_max: force/config/min_max.json

checkpoint: infer/force/Array-I/Diamond-I_Array-I/20250211_190213/epoch_40.pth
save_dir: infer/force/Array-I/{}

unseen: ["sphere_s", "triangle", "pacman", "cone", "wave", "torus"]
test_unseen: False

#Train
train: True
train_use_checkpoint: True                 
draw_force: True
draw_use_checkpoint: False 
     
#Infer
# train: False
# train_use_checkpoint: True                 
# draw_force: True
# draw_use_checkpoint: True              

num_workers: 16
batch_size: 2
n_epoch: 40
early_stop: 20
lr: 1e-3   #train 1e-1;fine tune:1e-3
seed: 0

