name: genforce
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - numpy
      - lpips
      - clean-fid
      - peft
      - dominate
      - tokenizers
      - tqdm
      - taichi
      - pytransform3d
      - imageio
      - open3d
      - scikit-image
      - opencv-python
      - clip @ git+https://github.com/openai/CLIP.git
      - torch>=2.0.1
      - torchdata==0.6.1
      - torchmetrics>=1.0.1
      - torchvision>=0.15.2
      - einops>=0.6.1
      - open-clip-torch>=2.20.0
      - pillow>=9.5.0
      - scipy==1.11.1
      - timm>=0.9.2
      - transformers==4.35.2
      - urllib3<1.27,>=1.25.4
      - xformers>=0.0.20
      - streamlit-keyup==0.2.0
      - diffusers==0.25.1
      - gradio==3.43.1
