name: genforce
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - numpy
      - lpips
      - clean-fid
      - peft
      - dominate
      - tokenizers
      - tqdm
      - taichi
      - pytransform3d
      - imageio
      - open3d
      - opencv-python
      - clip @ git+https://github.com/openai/CLIP.git
      - torch
      - torchdata
      - torchmetrics
      - torchvision
      - einops
      - open-clip-torch
      - pillow
      - scipy
      - timm
      - transformers
      - urllib3
      - xformers
      - streamlit-keyup
      - diffusers
      - gradio
      - wandb
      - vision-aided-loss
