task: uskin_gelsight

src_img: infer/heteroo/uskin_gelsight/02_25_21_14
src_force: dataset/hetero/force/uskin

tar_img: dataset/hetero/img/gelsight
tar_force: dataset/hetero/force/gelsight

min_max: force/config/min_max.json

checkpoint: infer/force/hetero/uskin_gelsight/20250215_155858/epoch_40.pth
save_dir: infer/force/hetero/{}

unseen: ["sphere_s", "triangle", "pacman", "cone", "wave", "torus", "dots"]
test_unseen: False

#Train
train: True
train_use_checkpoint: True                 
draw_force: True
draw_use_checkpoint: False 
     
#Infer
# train: False
# train_use_checkpoint: True                 
# draw_force: True
# draw_use_checkpoint: True               

num_workers: 16
batch_size: 4
n_epoch: 40
early_stop: 20
lr: 1e-3   #train 1e-1;fine tune:1e-3
seed: 0
