task: Array-II_Circle-II

src_img: dataset/homo/image/npy/Array-II
src_force: dataset/homo/force/Array-II

tar_img: dataset/homo/image/npy/Circle-II
tar_force: dataset/homo/force/Circle-II

min_max: force/config/min_max.json

checkpoint: infer/force_so/Circle-II/Array-II_Circle-II/20250119_032401/epoch_40.pth
save_dir: infer/force_so/Circle-II/{}

unseen: ["sphere_s", "triangle", "pacman", "cone", "wave", "torus"]
test_unseen: False

#Train
train: True
train_use_checkpoint: True                 
draw_force: True
draw_use_checkpoint: False 
     
# #Infer
# train: False
# train_use_checkpoint: True                 
# draw_force: True
# draw_use_checkpoint: True                

num_workers: 16
batch_size: 4
n_epoch: 40
early_stop: 20
lr: 1e-3   #train 1e-1;fine tune:1e-3
seed: 0
