task: gelsight_tactip

src_img: /scratch_tmp/grp/luo/zhuo/genforce/dataset/genforce/heterogeneous/location_pair/uskin_gelsight/img/18indenters/gelsight
src_force: /scratch_tmp/grp/luo/zhuo/genforce/dataset/genforce/heterogeneous/location_pair/uskin_gelsight/force/18indenters/gelsight

tar_img: /scratch_tmp/grp/luo/zhuo/genforce/dataset/genforce/heterogeneous/location_pair/uskin_gelsight/img/18indenters/tactip
tar_force: /scratch_tmp/grp/luo/zhuo/genforce/dataset/genforce/heterogeneous/location_pair/uskin_gelsight/force/18indenters/tactip

min_max: force/config/min_max.json

checkpoint: /scratch_tmp/users/k23058530/project/genforce/output/force/hetero/2types/uskin/18types/uskin_gelsight/20250210_042741/epoch_40.pth
save_dir: /scratch_tmp/users/k23058530/project/genforce/output/force/hetero/3types/so/{}

unseen: ["sphere_s", "triangle", "pacman", "cone", "wave", "torus"]
test_unseen: False

#Train
train: True
train_use_checkpoint: True                 
draw_force: True
draw_use_checkpoint: False 
     
#Infer
# train: False
# train_use_checkpoint: True                 
# draw_force: True
# draw_use_checkpoint: True               

num_workers: 16
batch_size: 2
n_epoch: 40
early_stop: 20
lr: 1e-3   #train 1e-1;fine tune:1e-3
seed: 0
