task: gelsight_tactip

src_img: dataset/hetero/img/gelsight
src_force: dataset/hetero/force/gelsight

tar_img: dataset/hetero/img/tactip
tar_force: dataset/hetero/force/tactip

min_max: force/config/min_max.json

checkpoint: infer/force_so/hetero/uskin_gelsight/20250210_042741/epoch_40.pth
save_dir: infer/force_so/hetero/{}

unseen: ["sphere_s", "triangle", "pacman", "cone", "wave", "torus"]
test_unseen: False

#Train
train: True
train_use_checkpoint: True                 
draw_force: True
draw_use_checkpoint: False 
     
#Infer
# train: False
# train_use_checkpoint: True                 
# draw_force: True
# draw_use_checkpoint: True               

num_workers: 16
batch_size: 2
n_epoch: 40
early_stop: 20
lr: 1e-3   #train 1e-1;fine tune:1e-3
seed: 0
