task: Circle-I_Array-II

src_img: infer/homo/Circle-I_Array-II/01_13_23_14
src_force: dataset/homo/force/Circle-I

tar_img: dataset/homo/image/npy/Array-II
tar_force: dataset/homo/force/Array-II

min_max: force/config/min_max.json

checkpoint: infer/force/Array-II/Array-I_Array-II/20250211_205151/epoch_40.pth
save_dir: infer/force/Array-II/{}

unseen: ["sphere_s", "triangle", "pacman", "cone", "wave", "torus"]
test_unseen: False

#Train
train: True
train_use_checkpoint: True                 
draw_force: True
draw_use_checkpoint: False 
     
#Infer
# train: False
# train_use_checkpoint: True                 
# draw_force: True
# draw_use_checkpoint: True                   

num_workers: 16
batch_size: 2
n_epoch: 40
early_stop: 20
lr: 1e-3   #train 1e-1;fine tune:1e-3
seed: 0

