task: GelTip2_GelSight1

src_img: infer/homo/GelTip2_GelSight1/01_13_18_48
src_force: dataset/homo/force/GelTip2

tar_img: dataset/homo/image/npy/GelSight1
tar_force: dataset/homo/force/GelSight1

min_max: force/config/min_max.json

checkpoint: infer/force/gelsight1/GelTip2_GelSight1/20250211_134327/epoch_40.pth
save_dir: infer/force/gelsight1/{}


unseen: ["sphere_s", "triangle", "pacman", "cone", "wave", "torus"]
test_unseen: False

#Train
train: True
train_use_checkpoint: True                 
draw_force: True
draw_use_checkpoint: False 
     
#Infer
# train: False
# train_use_checkpoint: True                 
# draw_force: True
# draw_use_checkpoint: True               

num_workers: 16
batch_size: 2
n_epoch: 40
early_stop: 20
lr: 1e-3   #train 1e-1;fine tune:1e-3
seed: 0

