task: Circle-II_Diamond-I

src_img: infer/homo/Circle-II_Diamond-I/01_14_05_47
src_force: dataset/homo/force/Circle-II

tar_img: dataset/homo/image/npy/Diamond-I
tar_force: dataset/homo/force/Diamond-I

min_max: force/config/min_max.json

checkpoint: infer/force/Diamond-I/Array-II_Diamond-I/20250211_065031/epoch_40.pth
save_dir: infer/force/Diamond-I/{}

unseen: ["sphere_s", "triangle", "pacman", "cone", "wave", "torus"]
test_unseen: False

#Train
train: True
train_use_checkpoint: True                 
draw_force: True
draw_use_checkpoint: False 
     
#Infer
# train: False
# train_use_checkpoint: True                 
# draw_force: True
# draw_use_checkpoint: True               

num_workers: 16
batch_size: 2
n_epoch: 40
early_stop: 20
lr: 1e-3   #train 1e-1;fine tune:1e-3
seed: 0
