task: GelSight2_TacTip2

src_img: dataset/homo/image/npy/GelSight2
src_force: dataset/homo/force/GelSight2

tar_img: dataset/homo/image/npy/TacTip2
tar_force: dataset/homo/force/TacTip2

min_max: force/config/min_max.json

checkpoint: infer/force_so/tactip2/GelSight2_TacTip2/20250119_063235/epoch_40.pth
save_dir: infer/force_so/tactip2/{}

unseen: ["sphere_s", "triangle", "pacman", "cone", "wave", "torus"]
test_unseen: False

#Train
train: True
train_use_checkpoint: True                 
draw_force: True
draw_use_checkpoint: False 
     
# #Infer
# train: False
# train_use_checkpoint: True                 
# draw_force: True
# draw_use_checkpoint: True                

num_workers: 16
batch_size: 4
n_epoch: 40
early_stop: 20
lr: 1e-3   #train 1e-1;fine tune:1e-3
seed: 0
