task: GelTip2_TacTip2

src_img: dataset/homo/image/npy/GelTip2
src_force: dataset/homo/force/GelTip2

tar_img: dataset/homo/image/npy/TacTip2
tar_force: dataset/homo/force/TacTip2

min_max: force/config/min_max.json

checkpoint: /scratch_tmp/users/k23058530/project/genforce/output/force/5types/source_only/incomplete/tactip2/GelTip2_TacTip2/20250119_111210/epoch_40.pth
save_dir: /scratch_tmp/users/k23058530/project/genforce/output/force/5types/source_only/tactip2/{}

#Train
# train: True
# train_use_checkpoint: True                 
# draw_force: True
# draw_use_checkpoint: False 
     
#Infer
train: False
train_use_checkpoint: True                 
draw_force: True
draw_use_checkpoint: True                 

num_workers: 32
batch_size: 4
n_epoch: 40
early_stop: 20
lr: 1e-3   #train 1e-1;fine tune:1e-3
seed: 0

unseen: ["cone","wave","triangle","pacman","cylinder-sh","sphere-s"]
