task: ratio_14_ratio_6

src_img: dataset/homo/infer/modulus/ratio_6/ratio_14_ratio_6/01_18_23_02
src_force: dataset/homo/modulus/force/ratio_14

tar_img: dataset/homo/modulus/image/ratio_6
tar_force: dataset/homo/modulus/force/ratio_6

min_max: force/config/min_max.json

checkpoint: infer/force_com/modulus/incomplete/ratio6/ratio_14_ratio_6/20250121_165315/epoch_40.pth
save_dir: infer/force_com/modulus/{}

#Train
# train: True
# train_use_checkpoint: True                 
# draw_force: True
# draw_use_checkpoint: False 
     
#Infer
train: False
train_use_checkpoint: True                 
draw_force: True
draw_use_checkpoint: True                

num_workers: 32
batch_size: 8
n_epoch: 40
early_stop: 20
lr: 1e-3   #train 1e-1;fine tune:1e-3
seed: 0

unseen: ["cone","wave","triangle","pacman","cylinder-sh","sphere-s"]
