task: tactip_uskin

src_img: infer/heteroo/tactip_uskin/02_26_07_38
src_force: dataset/hetero/force/tactip

tar_img: dataset/hetero/img/uskin
tar_force: dataset/hetero/force/uskin

min_max: force/config/min_max.json

checkpoint: infer/force_com/hetero/tactip_uskin/20250305_001512/epoch_20.pth
save_dir: infer/force_com/hetero/{}

src_depth: dataset/hetero/depth/tactip
modulus: dataset/material_compensatin/hetero/cofficient

unseen: ["sphere_s", "triangle", "pacman", "cone", "wave", "torus","dots"]
test_unseen: False

#Train
train: True
train_use_checkpoint: True                 
draw_force: True
draw_use_checkpoint: False 
     
#Infer
# train: False
# train_use_checkpoint: True                 
# draw_force: True
# draw_use_checkpoint: True               

num_workers: 16
batch_size: 4
n_epoch: 20
early_stop: 20
lr: 1e-3   #train 1e-1;fine tune:1e-3
seed: 0
