task: GelTip3_GelTip2

src_img: infer/homo/GelTip3_GelTip2/01_14_03_40
src_force: dataset/homo/force/GelTip3

tar_img: dataset/homo/image/npy/GelTip2
tar_force: dataset/homo/force/GelTip2

min_max: force/config/min_max.json

checkpoint: infer/force/geltip2/GelTip3_GelTip2/20250212_022559/epoch_40.pth
save_dir: /scratch_tmp/grp/luo/zhuo/genforce/infer/force/5types/unseen/m2m/geltip2/{}

unseen: ["sphere_s", "triangle", "pacman", "cone", "wave", "torus"]
test_unseen: True

#Infer
train: False
train_use_checkpoint: True                 
draw_force: True
draw_use_checkpoint: True               

num_workers: 16
batch_size: 4
n_epoch: 40
early_stop: 20
lr: 1e-3   #train 1e-1;fine tune:1e-3
seed: 0

