task: GelSight1_TacTip2

src_img: infer/homo/GelSight1_TacTip2/01_13_04_54
src_force: dataset/homo/force/GelSight1

tar_img: dataset/homo/image/npy/TacTip2
tar_force: dataset/homo/force/TacTip2

min_max: force/config/min_max.json

checkpoint: infer/force/tactip2/GelSight1_TacTip2/20250212_023258/epoch_40.pth
save_dir: /scratch_tmp/grp/luo/zhuo/genforce/infer/force/5types/unseen/m2m/tactip2/{}

unseen: ["sphere_s", "triangle", "pacman", "cone", "wave", "torus"]
test_unseen: True

#Infer
train: False
train_use_checkpoint: True                 
draw_force: True
draw_use_checkpoint: True               

num_workers: 16
batch_size: 2
n_epoch: 40
early_stop: 20
lr: 1e-3   #train 1e-1;fine tune:1e-3
seed: 0
