task: ratio_18-ratio_10

src_img: dataset/homo/infer/modulus/ratio_10/ratio_18_ratio_10/01_18_15_01
src_force: dataset/homo/modulus/force/ratio_18

tar_img: dataset/homo/modulus/image/ratio_10
tar_force: dataset/homo/modulus/force/ratio_10

min_max: force/config/min_max.json

checkpoint: infer/force_com/modulus/incomplete/ratio10/ratio_18_ratio_10/20250118_205733/epoch_40.pth
save_dir: infer/force_com/modulus_correction_depth0.8/{}

src_depth: dataset/homo/modulus/depth/ratio_18
modulus: dataset/homo/modulus/modulus

#Train
train: True
train_use_checkpoint: True                 
draw_force: True
draw_use_checkpoint: False 
     
#Infer
# train: False
# train_use_checkpoint: True                 
# draw_force: True
# draw_use_checkpoint: True                 

num_workers: 32
batch_size: 8
n_epoch: 40
early_stop: 20
lr: 1e-3   #train 1e-1;fine tune:1e-3
seed: 0

unseen: ["sphere_s", "triangle", "pacman", "cone", "wave", "torus"]
test_unseen: False