task: ratio_16_ratio_14

src_img: dataset/homo/infer/modulus/ratio_14/ratio_16_ratio_14/01_22_01_40
src_force: dataset/homo/modulus/force/ratio_16

tar_img: dataset/homo/modulus/image/ratio_14
tar_force: dataset/homo/modulus/force/ratio_14

min_max: force/config/min_max.json

checkpoint: infer/force_com/modulus/incomplete/ratio14/ratio_16_ratio_14/20250122_064318/epoch_40.pth
save_dir: infer/force_com/modulus/ori/{}


#Train
# train: True
# train_use_checkpoint: True                 
# draw_force: True
# draw_use_checkpoint: False 
     
#Infer
train: False
train_use_checkpoint: True                 
draw_force: True
draw_use_checkpoint: True                

num_workers: 32
batch_size: 4
n_epoch: 40
early_stop: 20
lr: 1e-3   #train 1e-1;fine tune:1e-3
seed: 0

unseen: ["cone","wave","triangle","pacman","cylinder-sh","sphere-s"]
