task: Circle-II_Circle-I

src_img: infer/homo/Circle-II_Circle-I/01_14_03_40
src_force: dataset/homo/force/Circle-II

tar_img: dataset/homo/image/npy/Circle-I
tar_force: dataset/homo/force/Circle-I

min_max: force/config/min_max.json

checkpoint: infer/force/Circle-I/Array-II_Circle-I/20250211_044039/epoch_30.pth
save_dir: infer/force/Circle-I/{}

unseen: ["sphere_s", "triangle", "pacman", "cone", "wave", "torus"]
test_unseen: False

#Train
train: True
train_use_checkpoint: True                 
draw_force: True
draw_use_checkpoint: False 
     
#Infer
# train: False
# train_use_checkpoint: True                 
# draw_force: True
# draw_use_checkpoint: True               

num_workers: 16
batch_size: 4
n_epoch: 40
early_stop: 20
lr: 1e-3   #train 1e-1;fine tune:1e-3
seed: 0

